#!/sbin/sh

TMPDIR=/tmp/hypercleaner
OUTFD=/proc/self/fd/$2
ZIPFILE="$3"

print() {
	echo -e "ui_print $1\nui_print" >> $OUTFD
}

waitForVolumeKey() {
	print "- 按音量[+]选择"是"，按音量[-]选择"否""
	keyInfo=true
	while $keyInfo; do
		keyInfo=$(getevent -qlc 1 | grep KEY_VOLUME)
		if [ "$keyInfo" == "" ]; then
			continue
		else
			isUpKey=$(echo $keyInfo | grep KEY_VOLUMEUP)
			[ "$isUpKey" != "" ] && return 0 || return 1
			break
		fi
	done
}

flash() {
	print "- 正在刷入分区 $(echo $2 | cut -d '/' -f 6)"
	7za e -so $ZIPFILE $1 > $2
}

flashZstd() {
	print "- 正在刷入分区 $(echo $2 | cut -d '/' -f 6)"
	7za e -so $ZIPFILE $1 | $TMPDIR/zstd -c -d > $2
}

remapSuper() {
	if [ -e /dev/block/mapper/$1 ]; then
		lptools unmap $1
		lptools map $1
	fi
}

lookupPackagePath() {
	for i in $(ls /data/app); do
		package=$(ls "/data/app/$i" | cut -d '-' -f 1)
		echo "$package:/data/app/$i" >> $TMPDIR/PackagePath.txt
	done
}

removeDataApp() {
	package=$(grep "^$1:" $TMPDIR/PackagePath.txt)
	path=$(echo $package | cut -d ':' -f 2)
	if [ -n "$path" ]; then
		rm -rf "$path"
	fi
}

rm -rf $TMPDIR
mkdir -p $TMPDIR

7za e $ZIPFILE META-INF/com/google/android/zstd -o$TMPDIR
chmod -R 0755 $TMPDIR

device=$(getprop ro.product.name)
print "=============================="
print " "
print "    < HyperCleaner >"
print " "
print "    https://github.com/meolunr/HyperCleaner"
print " "
print "    设备代号：$device"
print "    ROM 代号：$var_device"
print "    ROM 版本：$var_version"
print "    Android 版本：$var_sdk"
print " "
print "=============================="

if [ "$device" != "$var_device" ]; then
	print "- 设备代号与 ROM 代号不匹配，是否继续刷入？"
	if waitForVolumeKey; then
		print "- 继续刷入"
	else
		print "- 停止刷入"
		exit 1
	fi
fi

if [ $ZIPFILE != "/sideload/package.zip" ]; then
	print "- 正在校验 MD5"
	romName=$(basename $ZIPFILE)
	hashA=$(md5sum $ZIPFILE | head -c 10)
	hashB=$(echo $romName | cut -d '_' -f 4)

	if [ "$hashA" != "$hashB" ]; then
		print "- MD5 校验失败，可能是文件损坏或您修改过文件名，是否继续刷入？"
		if waitForVolumeKey; then
			print "- 继续刷入"
		else
			print "- 停止刷入"
			exit 1
		fi
	fi
fi

print "- 开始刷入"
$var_flash_img$var_remove_data_app
print "- 清除缓存"
rm -rf /data/cache
rm -rf /data/dalvik-cache
rm -rf /data/system/package_cache

print " "
print "- 已完成"
print " "
exit 0