#!/sbin/sh

outFd=/proc/self/fd/$2
zipFile="$3"

print() {
  echo -e "ui_print $1\nui_print" >>$outFd
}

waitForVolumeKey() {
	print "- 按音量[+]选择"是"，按音量[-]选择"否""
	keyInfo=true
	while $keyInfo; do
		keyInfo=$(getevent -qlc 1 | grep KEY_VOLUME)
		if [ "$keyInfo" == "" ]; then
			continue
		else
			isUpKey=$(echo $keyInfo | grep KEY_VOLUMEUP)
			[ "$isUpKey" != "" ] && return 0 || return 1
			break
		fi
	done
}

flash() {
  print "- 正在刷入分区 $(echo $2 | cut -d '/' -f 6)"
  unzip -p "$zipFile" $1 > $2
}

flashZstd() {
  print "- 正在刷入分区 $(echo $2 | cut -d '/' -f 6)"
  unzip -p "$zipFile" $1 | /tmp/META-INF/com/google/android/zstd -c -d > $2
}

remapSuper() {
	if [ -e /dev/block/mapper/$1 ]; then
	    lptools unmap $1
		lptools map $1
	fi
}

#####################################################################################

if [ -d /tmp ]; then
	rm -rf /tmp
fi
mkdir -p /tmp
unzip "$zipFile" META-INF/com/google/android/zstd -d /tmp
chmod -R 0755 /tmp

device=$(getprop ro.product.name)
print "=============================="
print " "
print "    < HyperCleaner >"
print " "
print "    https://github.com/meolunr/HyperCleaner"
print " "
print "    设备代号：$device"
print "    ROM 代号：$var_device"
print "    ROM 版本：$var_version"
print "    Android 版本：$var_sdk"
print " "
print "=============================="

if [ "$device" != "$var_device" ]; then
	print "- 设备代号与 ROM 代号不匹配，是否继续刷入？"
	if waitForVolumeKey; then
		print "- 继续刷入"
	else
		print "- 停止刷入"
		exit 1
	fi
fi

if [ "$zipFile" != "/sideload/package.zip" ]; then
	print "- 正在校验 MD5"
	romName=$(basename $zipFile)
	hashA=$(md5sum $zipFile |head -c 10)
	hashB=$(echo $romName |cut -d '_' -f 4)

	if [ "$hashA" != "$hashB" ]; then
		print "- MD5 校验失败，可能是文件损坏或您修改过文件名，是否继续刷入？"
		if waitForVolumeKey; then
			print "- 继续刷入"
		else
			print "- 停止刷入"
			exit 1
		fi
	fi
fi

print "- 开始刷入"
$var_flash_img
print "- 清除缓存"
rm -rf /data/dalvik-cache/arm/*
rm -rf /data/dalvik-cache/arm64/*
rm -rf /data/system/package_cache/*

print " "
print "- 已完成"
print " "
exit 0